FROM registry.cn-hangzhou.aliyuncs.com/google_containers/spark:1.5.1_v3
MAINTAINER 285414629@qq.com
#RUN /opt/spark/bin/spark-submit --packages datastax:spark-cassandra-connector:1.5.1-s_2.10
CMD ["opt/spark/bin/spark-submit", "--packages", "datastax:spark-cassandra-connector:1.5.1-s_2.10"]

